--PACIENTES COM ATENDIMENTO

SELECT 
lt.CD_LEITO,
lt.DS_LEITO,
TO_CHAR(mi.HR_MOV_INT, 'DD/MM/YYYY HH24:MI') as ENTRADA,
CASE
 WHEN atd.CD_ATENDIMENTO IS NULL THEN
  'RESERVA SEM ATENDIMENTO'
 ELSE
  pac.NM_PACIENTE
END AS NM_PACIENTE,
pac.TP_SEXO,
pac.CD_PACIENTE,
FLOOR((SYSDATE - pac.DT_NASCIMENTO) / 365.242199) AS IDADE,
lt.CD_LEITO,
lt.DS_RESUMO,
unid.DS_UNID_INT,
lt.CD_UNID_INT,
mi.CD_ATENDIMENTO,
esp.DS_ESPECIALID
FROM dbamv.LEITO lt

INNER JOIN dbamv.MOV_INT mi
  ON mi.CD_LEITO = lt.CD_LEITO
  
INNER JOIN dbamv.ATENDIME atd
  ON atd.CD_ATENDIMENTO = mi.CD_ATENDIMENTO
  
LEFT JOIN dbamv.PACIENTE pac
  ON pac.CD_PACIENTE = atd.CD_PACIENTE
  
INNER JOIN dbamv.UNID_INT unid
  ON unid.CD_UNID_INT = lt.CD_UNID_INT
  
LEFT JOIN dbamv.ESPECIALID esp
  ON esp.CD_ESPECIALID = atd.CD_ESPECIALID
  
WHERE mi.TP_MOV = 'R'
AND lt.CD_UNID_INT = 1
AND lt.TP_OCUPACAO = 'R'
AND mi.CD_MOV_INT IN (SELECT CD_MOV_INT
                      FROM dbamv.MOV_INT
                      WHERE TRUNC(DT_MOV_INT) BETWEEN TRUNC(SYSDATE - 1) and
                      TRUNC(SYSDATE)
                      AND TP_MOV = 'R')

UNION ALL

--PACIENTES SEM ATENDIMENTO

SELECT
lt.CD_LEITO,
lt.DS_LEITO,
TO_CHAR(rl.DT_PREV_INTERNACAO, 'DD/MM/YYYY HH24:MI') as ENTRADA,
pac.NM_PACIENTE,
pac.TP_SEXO,
pac.CD_PACIENTE,
FLOOR((SYSDATE - pac.DT_NASCIMENTO) / 365.242199) AS IDADE,
lt.CD_LEITO,
lt.DS_RESUMO,
unid.DS_UNID_INT,
lt.CD_UNID_INT,
rl.CD_ATENDIMENTO,
esp.DS_ESPECIALID

--SELECT *
FROM RES_LEI rl

LEFT JOIN dbamv.LEITO lt
  ON lt.CD_LEITO = rl.CD_LEITO
  
LEFT JOIN dbamv.PACIENTE pac
  ON pac.CD_PACIENTE = rl.CD_PACIENTE
  
LEFT JOIN dbamv.UNID_INT unid
  ON unid.CD_UNID_INT = lt.CD_UNID_INT
  
LEFT JOIN dbamv.ESPECIALID esp
  ON esp.CD_ESPECIALID = rl.CD_ESPECIALID
     
WHERE lt.CD_UNID_INT = 1
AND rl.CD_ATENDIMENTO IS NULL
AND SYSDATE BETWEEN rl.DT_RESERVA AND rl.DT_PREV_ALTA
