SELECT res.*
FROM(
SELECT 
CASE 
  WHEN UPPER(resp.DS_RESPOSTA) = 'OUTROS' THEN 'Outros:  ' || sel.DS_RESPOSTA
  ELSE resp.DS_RESPOSTA
END DS_RESPOSTA
--SELECT *
--SELECT DISTINCT sel.CD_PERGUNTA_HISTORICO, resp.DS_RESPOSTA
FROM dbamv.SAE_HISTORICO_ENFERMAGEM she
INNER JOIN dbamv.SAE_RESP_SELCND_HIST_ENFERMG sel
  ON sel.CD_HISTORICO_ENFERMAGEM = she.CD_HISTORICO_ENFERMAGEM
INNER JOIN dbamv.SAE_PERGUNTA_HISTORICO_ENFERMG perg
  ON perg.CD_PERGUNTA = sel.CD_PERGUNTA_HISTORICO
INNER JOIN dbamv.SAE_RESPOSTA_HISTORICO_ENFERMG resp
  ON sel.CD_RESPOSTA_HISTORICO = resp.CD_RESPOSTA
WHERE she.CD_ATENDIMENTO = 4725383
AND sel.CD_PERGUNTA_HISTORICO IN (216)
AND she.DT_INICIO = (SELECT MAX(sh.DT_INICIO)
                          FROM dbamv.SAE_HISTORICO_ENFERMAGEM sh
                          INNER JOIN dbamv.SAE_RESP_SELCND_HIST_ENFERMG sel
                            ON sel.CD_HISTORICO_ENFERMAGEM = sh.CD_HISTORICO_ENFERMAGEM
                         WHERE sh.cd_atendimento = 4725383
                         AND sel.CD_PERGUNTA_HISTORICO IN (216))) res
ORDER BY res.DS_RESPOSTA ASC                 
                     
                     


