SELECT g.*
FROM(
SELECT
'GANHOS' AS TIPO_BALANCO,
pbh.CD_BALANCO_HIDRICO, pbh.CD_ATENDIMENTO, 
pbh.CD_PACIENTE, pbh.DT_REFERENCIA,
--pitbh.DH_COLETA,
tp.CD_TIP_PRESC, tp.DS_TIP_PRESC,
SUM(pitbh.VL_COLETA) AS SUM_VL_COLETA
FROM dbamv.PW_BALANCO_HIDRICO pbh
INNER JOIN dbamv.PW_GRUPO_BALANCO_HIDRICO pgbh 
  ON pgbh.CD_BALANCO_HIDRICO = pbh.CD_BALANCO_HIDRICO
INNER JOIN dbamv.PW_ITBALANCO_HIDRICO pitbh
  ON pitbh.CD_GRUPO_BALANCO_HIDRICO = pgbh.CD_GRUPO_BALANCO_HIDRICO
INNER JOIN dbamv.TIP_PRESC tp
  ON tp.CD_TIP_PRESC = pitbh.CD_TIP_PRESC
AND pbh.CD_ATENDIMENTO = 4725383
AND pbh.DT_REFERENCIA IN (SELECT MAX(aux.DT_REFERENCIA) 
                          FROM dbamv.PW_BALANCO_HIDRICO aux
                          WHERE aux.CD_ATENDIMENTO = 4725383)
AND tp.TP_BALANCO = 'G'
GROUP BY pbh.CD_BALANCO_HIDRICO, pbh.CD_ATENDIMENTO, 
pbh.CD_PACIENTE, pbh.DT_REFERENCIA, 
--pitbh.DH_COLETA,
tp.CD_TIP_PRESC, tp.DS_TIP_PRESC, tp.DS_TIP_PRESC
ORDER BY tp.DS_TIP_PRESC ASC) g

UNION ALL 

SELECT p.*
FROM(
SELECT
'PERDAS' AS TIPO_BALANCO,
pbh.CD_BALANCO_HIDRICO, pbh.CD_ATENDIMENTO, 
pbh.CD_PACIENTE, pbh.DT_REFERENCIA,
--pitbh.DH_COLETA,
tp.CD_TIP_PRESC, tp.DS_TIP_PRESC,
SUM(pitbh.VL_COLETA) AS SUM_VL_COLETA
FROM dbamv.PW_BALANCO_HIDRICO pbh
INNER JOIN dbamv.PW_GRUPO_BALANCO_HIDRICO pgbh 
  ON pgbh.CD_BALANCO_HIDRICO = pbh.CD_BALANCO_HIDRICO
INNER JOIN dbamv.PW_ITBALANCO_HIDRICO pitbh
  ON pitbh.CD_GRUPO_BALANCO_HIDRICO = pgbh.CD_GRUPO_BALANCO_HIDRICO
INNER JOIN dbamv.TIP_PRESC tp
  ON tp.CD_TIP_PRESC = pitbh.CD_TIP_PRESC
AND pbh.CD_ATENDIMENTO = 4725383
AND pbh.DT_REFERENCIA IN (SELECT MAX(aux.DT_REFERENCIA) 
                          FROM dbamv.PW_BALANCO_HIDRICO aux
                          WHERE aux.CD_ATENDIMENTO = 4725383)
AND tp.TP_BALANCO = 'P'
GROUP BY pbh.CD_BALANCO_HIDRICO, pbh.CD_ATENDIMENTO, 
pbh.CD_PACIENTE, pbh.DT_REFERENCIA, 
--pitbh.DH_COLETA,
tp.CD_TIP_PRESC, tp.DS_TIP_PRESC
ORDER BY tp.DS_TIP_PRESC ASC) p
