SELECT DISTINCT hss.CD_DOCUMENTO_CLINICO, hss.CD_DOCUMENTO, hss.DS_DOCUMENTO,
hss.CD_PACIENTE, hss.CD_ATENDIMENTO,

(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
WHERE DS_IDENTIFICADOR = 'SC_EEPIA_CONDICOES_PELE_1' 
AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS CONDICOES_DE_PELE,
 
(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
 WHERE DS_IDENTIFICADOR = 'SC_EEPIA_DISP_CONTROLE_TROCA_1' 
 AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS DISP_CONTROLE_TROCA,
 
(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
WHERE DS_IDENTIFICADOR = 'SC_EEPIA_EDEMA_1' 
AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS SN_EDEMA,
 
(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
WHERE DS_IDENTIFICADOR = 'SC_EEPIA_ESTADO_EDEMA_1' 
AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS ESTADO_EDEMA,

(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
WHERE DS_IDENTIFICADOR = 'SC_EEPIA_CURATIVO_CP_1' 
AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS CURATIVO,

(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
WHERE DS_IDENTIFICADOR = 'SC_EEPIA_CARACTERISTICAS_CP_1' 
AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS CARACTERISTICAS,

(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
WHERE DS_IDENTIFICADOR = 'SC_EEPIA_SIST_GASTROINTESTINAL_1' 
AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS SISTEMA_GASTROINTESTINAL,

(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
WHERE DS_IDENTIFICADOR = 'SC_EEPIA_CONSIDERACOES_SIST_GASTRO_1' 
AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS CONSIDERACOES_GASTRO,

(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
WHERE DS_IDENTIFICADOR = 'SC_EEPIA_SIST_GENITURINARIO_1' 
AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS SISTEMA_GENITURINARIO,

(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
WHERE DS_IDENTIFICADOR = 'SC_EEPIA_CONSIDERACOES_SIST_GENITURINARIO_1' 
AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS CONSIDERACOES_GENITURINARIO,


(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
WHERE DS_IDENTIFICADOR = 'SC_EEPIA_HEMODINAMICAMENTE_TXT_1' 
AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS HEMODINAMICAMENTE,

(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
WHERE DS_IDENTIFICADOR = 'SC_EEPIA_USO_DVA_1' 
AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS SN_USO_DVA,

(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
WHERE DS_IDENTIFICADOR = 'SC_EEPIA_DVA_1' 
AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS QUAIS_VOLUMES,

(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
WHERE DS_IDENTIFICADOR = 'SC_EEPIA_NIVEL_CONSCIENCIA_1' 
AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS NIVEL_CONSCIENCIA,

(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
WHERE DS_IDENTIFICADOR = 'SC_EEPIA_NIVEL_CONSCIENCIA_1' 
AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS NIVEL_CONSCIENCIA,

(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
WHERE DS_IDENTIFICADOR = 'SC_EEPIA_CONSIDERACOES_SDC_1' 
AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS CONSIDERACOES_CONSCIENCIA,

(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
WHERE DS_IDENTIFICADOR = 'SC_EEPIA_MODO_VENTILATORIO_1' 
AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS MODO_VENTILATORIO,

(SELECT aux.DS_RESPOSTA FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR aux 
WHERE DS_IDENTIFICADOR = 'SC_EEPIA_CONSIDERACOES_MVENT_1' 
AND aux.CD_DOCUMENTO_CLINICO = hss.CD_DOCUMENTO_CLINICO) AS CONSIDERACOES_VENTILATORIO
  
FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR hss
WHERE hss.CD_DOCUMENTO = 979
AND hss.CD_ATENDIMENTO = 4462690
AND hss.CD_DOCUMENTO_CLINICO IN (SELECT MAX(doc.CD_DOCUMENTO_CLINICO)
                                 FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR doc
                                 WHERE doc.CD_DOCUMENTO = 979
                                 AND doc.CD_ATENDIMENTO = 4462690)
