SELECT *
FROM ALL_TAB_COLUMNS atc
WHERE atc.COLUMN_NAME LIKE '%CD_ALERTA_PROTOCOLO%'
AND atc.OWNER = 'DBAMV'
AND atc.TABLE_NAME IN (SELECT TABLE_NAME
                       FROM ALL_TAB_COLUMNS
                       WHERE COLUMN_NAME LIKE '%CD_PAC%'
                       AND OWNER = 'DBAMV');
                       
SELECT * FROM SAE_HISTORICO_ENFERMAGEM WHERE CD_ATENDIMENTO = 4513763;   

--DADOS GERAIS---
SELECT 
atd.CD_ATENDIMENTO,
unid.CD_UNID_INT, unid.DS_UNID_INT , lt.CD_LEITO, lt.DS_RESUMO,
pac.NM_PACIENTE, pac.DT_NAS
CIMENTO, 
conv.CD_CONVENIO, conv.NM_CONVENIO
FROM dbamv.ATENDIME atd
INNER JOIN dbamv.PACIENTE pac
  ON pac.CD_PACIENTE = atd.CD_PACIENTE
INNER JOIN dbamv.CONVENIO conv
  ON conv.CD_CONVENIO = atd.CD_CONVENIO
INNER JOIN dbamv.LEITO lt
  ON lt.CD_LEITO = atd.CD_LEITO
INNER JOIN dbamv.UNID_INT unid
  On unid.CD_UNID_INT = lt.CD_UNID_INT
WHERE atd.TP_ATENDIMENTO = 'I'
AND lt.CD_UNID_INT = 1
AND atd.DT_ALTA IS NULL
AND atd.DT_ALTA_MEDICA IS NULL
AND atd.CD_ATENDIMENTO = 4500181; --VARIAVEL PHP

--DIAGNOSTICOS--
--DIAGNOSTICO de internação: Pegar da tela MVPEP_ESTADIAMENTO
SELECT cid.CD_CID || ' (' || cid.DS_CID || ')' AS DS_DIAGNOSTICO
FROM dbamv.ATENDIME atd
INNER JOIN dbamv.CID cid
  ON cid.CD_CID = atd.CD_CID
WHERE atd.CD_ATENDIMENTO = '4547071';

--ISOLAMENTO--
--Isolamento: Grupos 475, 419, 289, 343 da tela M_SAE_GRU_PER_RES
SELECT resp.DS_RESPOSTA
FROM dbamv.SAE_HISTORICO_ENFERMAGEM she
INNER JOIN dbamv.SAE_RESP_SELCND_HIST_ENFERMG sel
  ON sel.CD_HISTORICO_ENFERMAGEM = she.CD_HISTORICO_ENFERMAGEM
INNER JOIN dbamv.SAE_PERGUNTA_HISTORICO_ENFERMG perg
  ON perg.CD_PERGUNTA = sel.CD_PERGUNTA_HISTORICO
INNER JOIN dbamv.SAE_RESPOSTA_HISTORICO_ENFERMG resp
  ON sel.CD_RESPOSTA_HISTORICO = resp.CD_RESPOSTA
WHERE sel.CD_PERGUNTA_HISTORICO IN (475, 419, 289, 343)
--AND resp.SN_ATIVO = 'S'
AND she.CD_ATENDIMENTO = 4513763;

--ALERGIAS---
--Alergias : tela MVPEP_ALERGIA_PACIENTE 
SELECT sub.DS_SUBSTANCIA || ' (' || hsp.DS_AVISO || ')' AS DS_ALERGIA
FROM HIST_SUBS_PAC hsp
INNER JOIN dbamv.SUBSTANCIA sub
  ON sub.CD_SUBSTANCIA = hsp.CD_SUBSTANCIA
WHERE hsp.TP_ALERGIA = 'S'
AND hsp.CD_PACIENTE = 734348
ORDER BY 1 DESC;

--COMORBIDADES--
--Comorbidades: SC_EEPIA_HPP_1
SELECT hr.DS_RESPOSTA
FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR hr
WHERE hr.DS_IDENTIFICADOR = 'SC_EEPIA_HPP_1'
AND hr.DS_RESPOSTA IS NOT NULL
AND hr.CD_ATENDIMENTO = 4416357 --VARIAVEL PHP
AND hr.DH_IMPRESSO IN (SELECT MAX(hr_aux.DH_IMPRESSO) AS MAX_DH_IMPRESSO
                       FROM dbamv.VDIC_RESPOSTA_METADADO_HEITOR hr_aux
                       WHERE hr_aux.DS_IDENTIFICADOR = 'SC_EEPIA_HPP_1'
                       AND hr_aux.DS_RESPOSTA IS NOT NULL
                       AND hr_aux.CD_ATENDIMENTO = 4416357); --VARIAVEL PHP
                       
--VENTILACAO--
--VENT: Grupos - 467, 483, 348, 234, 346, 313
SELECT resp.DS_RESPOSTA
FROM dbamv.SAE_HISTORICO_ENFERMAGEM she
INNER JOIN dbamv.SAE_RESP_SELCND_HIST_ENFERMG sel
  ON sel.CD_HISTORICO_ENFERMAGEM = she.CD_HISTORICO_ENFERMAGEM
INNER JOIN dbamv.SAE_PERGUNTA_HISTORICO_ENFERMG perg
  ON perg.CD_PERGUNTA = sel.CD_PERGUNTA_HISTORICO
INNER JOIN dbamv.SAE_RESPOSTA_HISTORICO_ENFERMG resp
  ON sel.CD_RESPOSTA_HISTORICO = resp.CD_RESPOSTA
WHERE sel.CD_PERGUNTA_HISTORICO IN (467, 483, 348, 234, 346, 313)
--AND resp.SN_ATIVO = 'S'
AND she.CD_ATENDIMENTO = 4513763;

--DIETA/JEJUM--
--DIETA/JEJUM : Verificar o que esta prescrito pro paciente dos esquemas:
--DIE, DET, FOR, DEP, DPM, PNT, HID, SUP, MOD, SSR, DLS,LM,JEJ
SELECT DISTINCT tp.DS_TIP_PRESC
FROM dbamv.PRE_MED pm
INNER JOIN dbamv.ITPRE_MED itpm
  ON itpm.CD_PRE_MED = pm.CD_PRE_MED
INNER JOIN dbamv.TIP_PRESC tp
  ON tp.CD_TIP_PRESC = itpm.CD_TIP_PRESC
WHERE itpm.CD_TIP_ESQ IN ('DIE', 'DET', 'FOR', 'DEP', 'DPM', 'PNT', 'HID', 'SUP', 'MOD', 'SSR', 'DLS', 'LM', 'JEJ')
AND pm.CD_ATENDIMENTO = 4489270 --VARIAVEL PHP
AND pm.CD_PRE_MED IN (SELECT MAX(aux_pm.CD_PRE_MED) AS MAX_CD_PRE_MED 
                      FROM dbamv.PRE_MED aux_pm
                      INNER JOIN dbamv.ITPRE_MED aux_itpm
                        ON aux_itpm.CD_PRE_MED = aux_pm.CD_PRE_MED
                      WHERE aux_itpm.CD_TIP_ESQ IN ('DIE', 'DET', 'FOR', 'DEP', 'DPM', 'PNT', 'HID', 'SUP', 'MOD', 'SSR', 'DLS', 'LM', 'JEJ')
                      AND aux_pm.CD_ATENDIMENTO = 4489270); --VARIAVEL PHP
                      
--DISPOSITIVOS--
--DISPOSITIVOS: Grupo 329, resposta 2695 ; 341, 338, 342, 340
SELECT resp.DS_RESPOSTA
FROM dbamv.SAE_HISTORICO_ENFERMAGEM she
INNER JOIN dbamv.SAE_RESP_SELCND_HIST_ENFERMG sel
  ON sel.CD_HISTORICO_ENFERMAGEM = she.CD_HISTORICO_ENFERMAGEM
INNER JOIN dbamv.SAE_PERGUNTA_HISTORICO_ENFERMG perg
  ON perg.CD_PERGUNTA = sel.CD_PERGUNTA_HISTORICO
INNER JOIN dbamv.SAE_RESPOSTA_HISTORICO_ENFERMG resp
  ON sel.CD_RESPOSTA_HISTORICO = resp.CD_RESPOSTA
WHERE sel.CD_PERGUNTA_HISTORICO IN (2695, 341, 338, 342, 340)
--AND resp.SN_ATIVO = 'S'
AND she.CD_ATENDIMENTO = 4513763;

--ELIMINACOES--
--ELIMINAÇÕES: Grupos 472, 367, 219
SELECT resp.DS_RESPOSTA
FROM dbamv.SAE_HISTORICO_ENFERMAGEM she
INNER JOIN dbamv.SAE_RESP_SELCND_HIST_ENFERMG sel
  ON sel.CD_HISTORICO_ENFERMAGEM = she.CD_HISTORICO_ENFERMAGEM
INNER JOIN dbamv.SAE_PERGUNTA_HISTORICO_ENFERMG perg
  ON perg.CD_PERGUNTA = sel.CD_PERGUNTA_HISTORICO
INNER JOIN dbamv.SAE_RESPOSTA_HISTORICO_ENFERMG resp
  ON sel.CD_RESPOSTA_HISTORICO = resp.CD_RESPOSTA
WHERE sel.CD_PERGUNTA_HISTORICO IN (472, 367, 219)
--AND resp.SN_ATIVO = 'S'
AND she.CD_ATENDIMENTO = 4513763;

--CURATIVOS-- 
--CURATIVOS/CONDIÇÕES DA PELE : 232, 342, 460, 336, 337
SELECT resp.DS_RESPOSTA
FROM dbamv.SAE_HISTORICO_ENFERMAGEM she
INNER JOIN dbamv.SAE_RESP_SELCND_HIST_ENFERMG sel
  ON sel.CD_HISTORICO_ENFERMAGEM = she.CD_HISTORICO_ENFERMAGEM
INNER JOIN dbamv.SAE_PERGUNTA_HISTORICO_ENFERMG perg
  ON perg.CD_PERGUNTA = sel.CD_PERGUNTA_HISTORICO
INNER JOIN dbamv.SAE_RESPOSTA_HISTORICO_ENFERMG resp
  ON sel.CD_RESPOSTA_HISTORICO = resp.CD_RESPOSTA
WHERE sel.CD_PERGUNTA_HISTORICO IN (232, 342, 460, 336, 337)
--AND resp.SN_ATIVO = 'S'
AND she.CD_ATENDIMENTO = 4513763;

--AVALIACOES--
--PARECER MEDICO: Verificar quais foram solicitadas nas ultimas 24 horas. Mostrar
--o status do parecer (pendente, respondido?) - tela: MVPEP_PARECER_MEDICO_SOLIC
SELECT 'PARECER: (' || pm.DT_SOLICITACAO || ') '|| esp.DS_ESPECIALID || ' [' || pm.DS_SITUACAO || '] ' AS DS_DESCRICAO
FROM dbamv.PAR_MED pm
INNER JOIN dbamv.ESPECIALID esp
  ON esp.CD_ESPECIALID = pm.CD_ESPECIALID
WHERE pm.CD_ATENDIMENTO = 4549276

UNION ALL

--CIRURGIAS: Cirurgias agendadas para o paciente
SELECT 'CIRURGIA : (' || ac.DT_INICIO_CIRURGIA || ') '|| cir.DS_CIRURGIA AS DS_DESCRICAO
FROM dbamv.AVISO_CIRURGIA ac
INNER JOIN dbamv.CIRURGIA_AVISO ca
  ON ca.CD_AVISO_CIRURGIA = ac.CD_AVISO_CIRURGIA
INNER JOIN dbamv.CIRURGIA cir
  ON cir.CD_CIRURGIA = ca.CD_CIRURGIA
WHERE ac.TP_SITUACAO = 'A'
AND ac.CD_ATENDIMENTO = 4553756

UNION ALL

--EXAMES : Exames prescritos pro paciente do esquema EXA e informar se laudo já está disponivel
--Exames prescritos pro paciente do esquema LAB e se está checado. se não estiver checado, mostrar a FREQUÊNCIA do item
SELECT 
CASE
  WHEN itrx.CD_LAUDO IS NOT NULL THEN 'EXAMES : (' || pm.DT_PRE_MED || ') '
       || tp.DS_TIP_PRESC || ' [LAUDO: ' || ld.HR_LAUDO || ']'
  ELSE 'EXAMES : (' || pm.DT_PRE_MED || ') '|| tp.DS_TIP_PRESC 
       || ' [LAUDO: AGUARDANDO]'
END AS DS_DESCRICAO
FROM dbamv.PRE_MED pm
INNER JOIN dbamv.ITPRE_MED itpm
  ON itpm.CD_PRE_MED = pm.CD_PRE_MED 
INNER JOIN dbamv.TIP_PRESC tp
  ON tp.CD_TIP_PRESC = itpm.CD_TIP_PRESC
INNER JOIN dbamv.ITPED_RX itrx
  ON itrx.CD_ITPRE_MED = itpm.CD_ITPRE_MED
LEFT JOIN dbamv.LAUDO_RX ld
  ON ld.CD_LAUDO = itrx.CD_LAUDO
WHERE itpm.CD_TIP_ESQ IN ('EXA')
AND pm.CD_ATENDIMENTO = 4554466

UNION ALL 

SELECT 'EXAMES LABORATORIAIS : (' || pm.DT_PRE_MED || ') '|| tp.DS_TIP_PRESC || ' [' || tf.DS_TIP_FRE || ']' AS DS_DESCRICAO
FROM dbamv.PRE_MED pm
INNER JOIN dbamv.ITPRE_MED itpm
  ON itpm.CD_PRE_MED = pm.CD_PRE_MED 
INNER JOIN dbamv.TIP_PRESC tp
  ON tp.CD_TIP_PRESC = itpm.CD_TIP_PRESC
INNER JOIN dbamv.TIP_FRE tf
  ON tf.CD_TIP_FRE = itpm.CD_TIP_FRE
WHERE itpm.CD_TIP_ESQ IN ('LAB')
AND pm.CD_ATENDIMENTO = 4554466;

--PROTOCOLOS--
--PROTOCOLOS CLÍNICOS ABERTOS: Tela de alertas de protocolo. Mostrar a descrição do alerta e em qual etapa está 

SELECT * 
FROM dbamv.PW_CASO_PROTOCOLO cp
INNER JOIN dbamv.PW_ALERTA_PROTOCOLO ap
  ON ap.CD_ALERTA_PROTOCOLO = cp.CD_ALERTA_PROTOCOLO
WHERE CD_PACIENTE = 403831;
