--EXCLUIR VINCULOS FKs
--ALTER TABLE portal_cadastro.REGRA DROP CONSTRAINT fk_cd_tipo_regra;

---------
--SETOR--
---------
DROP SEQUENCE escala_medica.SEQ_CD_SETOR; 
CREATE SEQUENCE escala_medica.SEQ_CD_SETOR 
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

DROP SEQUENCE escala_medica.SEQ_CD_EXAME; 
CREATE SEQUENCE escala_medica.SEQ_CD_EXAME 
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

DROP TABLE escala_medica.DIVISAO_HORA;
create table DIVISAO_HORA
(
  tp_hora VARCHAR2(1) not null,
  ds_hora VARCHAR2(5) not null
);
--essa tabela sera alimentada assim que abrir a home


DROP TABLE escala_medica.SETOR;
CREATE TABLE escala_medica.SETOR(

CD_SETOR            INT NOT NULL,
CD_ESPECIALID       INTEGER,
TP_SETOR            VARCHAR(1) NOT NULL,
SN_EXAME            VARCHAR(1) NOT NULL,
CD_EXAME            INTEGER,
DS_SETOR            VARCHAR(50) NOT NULL,
CD_PRESTADOR_MV     INT NOT NULL,
CD_CONSELHO         VARCHAR2(30) NOT NULL,
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO         TIMESTAMP NOT NULL,
CD_USUARIO_ULT_ALT  VARCHAR(20),
HR_ULT_ALT          TIMESTAMP,

--PRIMARY KEY
CONSTRAINT pk_cd_setor PRIMARY KEY (CD_SETOR),

--TRAVA DE CARACTER TP SETOR (D OU P)
CONSTRAINT check_tp_setor CHECK (TP_SETOR IN ('D', 'P', 'F'))

--KEY (CHAVE ESTRANGEIRA) CONEXAO COM dbamv.PRESTADOR
--CONSTRAINT fk_cd_prestador_mv FOREIGN KEY (CD_PRESTADOR_MV) REFERENCES dbamv.PRESTADOR(CD_PRESTADOR)

);


DROP TABLE escala_medica.ESCALA;
CREATE TABLE ESCALA
(
  CD_ESCALA           INTEGER not null,
  PERIODO             VARCHAR2(7) not null,
  CD_SETOR            INTEGER not null,
  CD_PRESTADOR_MV     INTEGER not null,
  DIA                 INTEGER,
  DIARISTA            VARCHAR2(1),
  HR_INICIAL          VARCHAR2(5),
  HR_FINAL            VARCHAR2(5),
  CD_USUARIO_CADASTRO VARCHAR2(20) not null,
  HR_CADASTRO         TIMESTAMP(6) not null,
  CD_USUARIO_ULT_ALT  VARCHAR2(20),
  HR_ULT_ALT          TIMESTAMP(6),

  CONSTRAINT PK_CD_ESCALA PRIMARY KEY (CD_ESCALA)


);

COMMENT ON COLUMN escala_medica.SETOR.CD_SETOR IS 'SEQ_CD_SETOR';
COMMENT ON COLUMN escala_medica.SETOR.TP_SETOR IS 'D - Distancia | P - Presencial | F - Fixa';

DELETE escala_medica.EXAME;
DROP TABLE escala_medica.EXAME;

CREATE TABLE escala_medica.EXAME
(
  CD_EXAME            INTEGER NOT NULL,
  DS_EXAME            VARCHAR2(40) NOT NULL,
  CD_ESPECIALIDADE    INTEGER NOT NULL,
  CD_USUARIO_CADASTRO VARCHAR2(20) NOT NULL,
  HR_CADASTRO         TIMESTAMP(6) NOT NULL,
  CD_USUARIO_ULT_ALT  VARCHAR2(20),
  HR_ULT_ALT          TIMESTAMP(6)

);

--CRIANDO TABELA PASSAGEM PLANTAO--


DROP TABLE passagem_plantao.PERMISSOES;

CREATE TABLE passagem_plantao.PERMISSOES(
CD_PERMISSAO        INT NOT NULL,
CD_USUARIO          VARCHAR(20) NOT NULL,
CD_UNID_INT         INT NOT NULL,
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO         TIMESTAMP NOT NULL,
CD_USUARIO_ULT_ALT  VARCHAR(20),
HR_ULT_ALT          TIMESTAMP,

CONSTRAINT PK_PERMISSOES PRIMARY KEY (CD_PERMISSAO),
CONSTRAINT UK_PERMISSOES UNIQUE (CD_USUARIO, CD_UNID_INT)

);

--CRIANDO UMA SEQUENCE--
DROP SEQUENCE passagem_plantao.SEQ_PERMISSOES;

CREATE SEQUENCE passagem_plantao.SEQ_PERMISSOES
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

--VISUALIZANDO A TABELA--
SELECT * FROM passagem_plantao.PERMISSOES

--ALIMENTANDO TABELA--

INSERT INTO passagem_plantao.PERMISSOES
SELECT passagem_plantao.Seq_Permissoes.NEXTVAL CD_PERMISSAO,
'LDPGOMES' AS CD_USUARIO,
'49' AS CD_UNID_INT,
'HSSAMPAIO' AS CD_USUARIO_CADASTRO,
SYSDATE HR_CADASTRO,
NULL CD_USUARIO_ULT_ALT,
NULL HR_ULT_ALT
FROM DUAL ;

----- Criando Tabela Durante -----

DROP TABLE passagem_plantao.DURANTE;

CREATE TABLE passagem_plantao.DURANTE(
CD_DURANTE           INT NOT NULL,
DT_PLANTAO           TIMESTAMP,
CD_UNID_INT          INT NOT NULL,
EQUIP_SN             VARCHAR(1),
EQUIP_DESC           VARCHAR(100),
CAR_SN               VARCHAR(1),
REP_LAC_SN           VARCHAR(1),
LACRE_DESC           VARCHAR(20),
LT_BLOQ_SN           VARCHAR(1),
LT_MOTIVO_DESC       VARCHAR(50),
FT_MM_SN             VARCHAR(1),
MM_DESC              VARCHAR(50),
FARM_SN              VARCHAR(1),
PPF_SN               VARCHAR(1),
CONDUTA_DESC         VARCHAR(100),
IP_SN                VARCHAR(1),
IP_DESC              VARCHAR(100),
CD_USUARIO_CADASTRO  VARCHAR(20) NOT NULL,
HR_CADASTRO          TIMESTAMP NOT NULL,
CD_USUARIO_ULT_ALT   VARCHAR(20),
HR_ULT_ALT           TIMESTAMP,

CONSTRAINT PK_DURANTE PRIMARY KEY (CD_DURANTE)

);

-----CRIANDO A SEQUENCE-----
DROP SEQUENCE passagem_plantao.SEQ_DURANTE;

CREATE SEQUENCE passagem_plantao.SEQ_DURANTE
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

-----Visualizando Tabela-----
select * from passagem_plantao.durante

-----Alimentando Tabela-----

INSERT INTO passagem_plantao.durante
SELECT passagem_plantao.seq_durante.NEXTVAL CD_DURANTE,
SYSDATE AS DT_PLANTAO,
'49' AS CD_UNID_INT,
'S' AS EQUIP_SN,
'computador nao liga' AS EQUIP_DESC,
'S' AS CAR_SN,
'S' AS REP_LAC_SN,
'1b2c3a' AS LACRE_DESC,
'N' AS LT_BLOQ_SN,
'livre' AS LT_MOTIVO_DESC,
'S' AS FT_MM_SN,
'dipirona' AS MM_DESC,
'S' as FARM_SN,
'N' AS PPF_SN,
'caso ok' AS CONDUTA_DESC,
'N'AS IP_SN,
'nenhum' AS IP_DESC,
'LDPGOMES' AS CD_USUARIO_CADASTRO,
SYSDATE HR_CADASTRO,
NULL CD_USUARIO_ULT_ALT,
NULL HR_ULT_ALT
FROM DUAL ;

----SELECT HISTORICO DE PASSAGENS----

SELECT * FROM passagem_plantao.durante

SELECT * FROM dbamv.unid_int

SELECT * FROM dbasgu.usuarios


SELECT PPD.CD_UNID_INT, 
      UI.DS_UNID_INT, 
      PPD.CD_USUARIO_CADASTRO, 
      USU.NM_USUARIO,
      TO_CHAR(PPD.HR_CADASTRO, 'DD/MM/YYYY HH24:MI:SS') AS DIA
       FROM passagem_plantao.durante PPD
       INNER JOIN dbamv.unid_int UI
             ON UI.CD_UNID_INT = PPD.CD_UNID_INT
       INNER JOIN dbasgu.usuarios USU
             ON PPD.CD_USUARIO_CADASTRO = USU.CD_USUARIO
       WHERE PPD.CD_UNID_INT = '1'
       AND EXTRACT (YEAR FROM PPD.HR_CADASTRO) = 2022
       AND EXTRACT (MONTH FROM PPD.HR_CADASTRO) = 07
       
       
       SELECT * FROM 

-----CRIANDO TABELA OBSERVACAO ESPECIAL-----

DROP TABLE passagem_plantao.OBSERVACAO_ESPECIAL;

CREATE TABLE passagem_plantao.OBSERVACAO_ESPECIAL (
       CD_OBSERVACAO INT,
       CD_PACIENTE INT,
       CD_USUARIO_CRIACAO VARCHAR(20),
       HR_CRIACAO TIMESTAMP,
       OBSERVACAO VARCHAR(200),
       SN_SOLUCIONADO VARCHAR(1),
       HR_SOLUCIONADO TIMESTAMP,
       CD_USUARIO_SOLUCIONADO VARCHAR(20)
);

-----CRIANDO A SEQUENCE-----
DROP SEQUENCE passagem_plantao.SEQ_OBS_ESPECIAL;

CREATE SEQUENCE passagem_plantao.SEQ_OBS_ESPECIAL
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

-----CRIANDO TABELA OBSERVACAO PACIENTE-----

DROP TABLE passagem_plantao.OBSERVACAO_PACIENTE;


CREATE TABLE passagem_plantao.OBSERVACAO_PACIENTE (
       CD_OBSERVACAO INT,
       CD_SETOR INT,
       CD_DURANTE INT,
       CD_USUARIO_CRIACAO VARCHAR(20),
       HR_CRIACAO TIMESTAMP,
       OBSERVACAO VARCHAR(200)
);

-----CRIANDO A SEQUENCE-----
DROP SEQUENCE passagem_plantao.SEQ_OBS_PACIENTE;

CREATE SEQUENCE passagem_plantao.SEQ_OBS_PACIENTE
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

-----CRIANDO TABELA OBSERVACAO INTERCORRENCIA-----

DROP TABLE passagem_plantao.OBSERVACAO_INTERCORRENCIA;


CREATE TABLE passagem_plantao.OBSERVACAO_INTERCORRENCIA (
       CD_OBSERVACAO INT,
       CD_SETOR INT,
       CD_DURANTE INT,
       CD_USUARIO_CRIACAO VARCHAR(20),
       HR_CRIACAO TIMESTAMP,
       OBSERVACAO VARCHAR(200)
);

-----CRIANDO A SEQUENCE-----
DROP SEQUENCE passagem_plantao.SEQ_OBS_INTERCORRENCIA;

CREATE SEQUENCE passagem_plantao.SEQ_OBS_INTERCORRENCIA
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;

-----CRIANDO TABELA QUADRO ENFERMAGEM-----
DROP TABLE passagem_plantao.quadro_enf;

create table quadro_enf (
       cd_anotacao int,
       cd_leito int,
       cd_paciente int,
       CD_UNID_INT int,
       obs VARCHAR2(200),
       dt_anotacao timestamp,
       TP_ANOTACAO VARCHAR(3),
       CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
       HR_CADASTRO         TIMESTAMP NOT NULL,
       CD_USUARIO_ULT_ALT  VARCHAR(20),
       HR_ULT_ALT          TIMESTAMP
       );

DROP SEQUENCE passagem_plantao.SEQ_OBS_QUADRO;

CREATE SEQUENCE passagem_plantao.SEQ_OBS_QUADRO
START WITH 1
INCREMENT BY 1
NOCACHE 
NOCYCLE;




















