--EXCLUIR VINCULOS FKs
--ALTER TABLE portal_cadastro.REGRA DROP CONSTRAINT fk_cd_tipo_regra;

---------
--SETOR--
---------

DROP TABLE escala_medica.SETOR;
CREATE TABLE escala_medica.SETOR(

CD_SETOR            INT NOT NULL,
TP_SETOR            VARCHAR(1) NOT NULL,
DS_SETOR            VARCHAR(50) NOT NULL,
CD_PRESTADOR_MV     INT NOT NULL,
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO         TIMESTAMP NOT NULL,
CD_USUARIO_ULT_ALT  VARCHAR(20),
HR_ULT_ALT          TIMESTAMP,

--PRIMARY KEY
CONSTRAINT pk_cd_setor PRIMARY KEY (CD_SETOR),

--TRAVA DE CARACTER TP SETOR (D OU P)
CONSTRAINT check_tp_setor CHECK (TP_SETOR IN ('D', 'P')),

--FOREING KEY (CHAVE ESTRANGEIRA) CONEXAO COM dbamv.PRESTADOR
CONSTRAINT fk_cd_prestador_mv FOREIGN KEY (CD_PRESTADOR_MV) REFERENCES dbamv.PRESTADOR(CD_PRESTADOR)

);

DROP SEQUENCE escala_medica.SEQ_CD_SETOR; 
CREATE SEQUENCE escala_medica.SEQ_CD_SETOR 
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

COMMENT ON COLUMN escala_medica.SETOR.CD_SETOR IS 'SEQ_CD_SETOR';
COMMENT ON COLUMN escala_medica.SETOR.TP_SETOR IS 'D - Distancia | P - Presencial';
